# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            tcollins
tagline:          'thoughts'
description:      'I like to write software and do other stuff. <a href="https://twitter.com/tim_collins" target="_blank">@tim_collins</a>'
url:              http://tcollins.github.io

author:
  name:           'Tim Collins'
  url:            https://twitter.com/tim_collins

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/tcollins
